from config import host_stage, host_prod

urls = [
    host_stage + "101internet.ru/",
    host_stage + "101internet.ru/orders/tohome",
    host_stage + "101internet.ru/address",
    host_stage + "101internet.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_stage + "101internet.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_stage + "101internet.ru/dom/ul-vinokurova-d-2-str1-id30677",
    host_stage + "101internet.ru/doma-nzl?house_id=135510",
    host_stage + "101internet.ru/reviews",
    host_stage + "101internet.ru/rating/mts",
    host_stage + "101internet.ru/feedback",
    host_stage + "101internet.ru/rating",
    host_stage + "101internet.ru/providers",
    host_stage + "101internet.ru/providers/dom-ru",
    host_stage + "101internet.ru/providers/dom-ru/rates",
    host_stage + "101internet.ru/providers/dom-ru/rates/domashnij-internet",
    host_stage + "101internet.ru/providers/dom-ru/rates/internet-i-tv",
    host_stage + "101internet.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "101internet.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage + "101internet.ru/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_stage + "101internet.ru/rates",
    host_stage + "101internet.ru/rates/domashnij-internet",
    host_stage + "101internet.ru/rates/internet-i-tv",
    host_stage + "101internet.ru/rates/internet-tv-mobile",
    host_stage + "101internet.ru/rates/internet-i-mobilnaya-svyaz",
    host_stage + "101internet.ru/rates/nedorogoj-domashnij-internet",
    host_stage + "101internet.ru/rates/internet-100-mbit",
    host_stage + "101internet.ru/rates/internet-300-mbit",
    host_stage + "101internet.ru/rates/internet-500-mbit",
    host_stage + "101internet.ru/orders/sat",
    host_stage + "101internet.ru/orders/office",
    host_stage + "101internet.ru/all-districts",
    host_stage + "101internet.ru/site-map",
    host_stage + "101internet.ru/about/personal-data",
    host_stage + "101internet.ru/about/documents",
    host_stage + "101internet.ru/about/partners",
    host_stage + "101internet.ru/about/company",
    host_stage + "101internet.ru/about/contacts",
    host_stage + "101internet.ru/about/oplata-i-garantii",
    host_stage + "101internet.ru/select-region",
    host_stage + "101internet.ru/providers/dom-ru/rates/internet-100-mbit",
    host_stage + "101internet.ru/providers/dom-ru/rates/internet-300-mbit",
    host_stage + "101internet.ru/providers/dom-ru/rates/internet-500-mbit",
    host_stage + "101internet.ru/providers/actions/mts",
    host_stage + "101internet.ru/providers/dom-ru/rates/online-kinoteatr",
    host_stage + "101internet.ru/rates/online-kinoteatr",
    host_stage + "101internet.ru/actions",
    host_stage + "101internet.ru/business",
    host_stage + "101internet.ru/contact-feedback"
]

names = [
"Главная",
"Поиск по адресу",
"Карта покрытия",
"Районы",
"Улицы",
"Золотой дом",
"Обычный дом",
"Отзывы в регионе",
"Отзывы провайдера",
"Страница оставления отзыва",
"Рейтинг",
"Каталог",
"Страница провайдера",
"Тарифы провайдера (тег Все)",
"Тарифы провайдера, тег Домашний интернет",
"Тарифы провайдера, тег Интернет + ТВ",
"Тарифы провайдера, тег Интернет + ТВ+ мобильная связь",
"Тарифы провайдера, тег Интернет + Мобильная связь",
"Тарифы провайдера, тег Акции ",
"Тарифы в регионе",
"Тарифы в регионе, тег Домашний интернет",
"Тарифы в регионе, тег Интернет + ТВ",
"Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
"Тарифы в регионе, тег Интернет + Мобильная связь",
"Тарифы в регионе, тег Акции",
"Тарифы в регионе, тег 100 Мб/с",
"Тарифы в регионе, тег 300 Мб/с",
"Тарифы в регионе, тег 500 Мб/с",
"На дачу",
"В офис",
"Все районы",
"Карта сайта",
"Политика обработки перс данных",
"Документы",
"Сотрудничество",
"О нас",
"Контакты",
"Оплата и гарантии",
"Селект регион",
"Тарифы провайдера, тег 100 Мб/с",
"Тарифы провайдера, тег 300 Мб/с",
"Тарифы провайдера, тег 500 Мб/с",
"Тарифы провайдера, тег Акции ",
"Тарифы провайдера, тег Онлайн кинотеатр",
"Тарифы в регионе, тег Онлайн кинотеатр",
"Акции в регионе",
"Офисная заявка (старая)",
"Форма обратной связи"
]

urls_prod = [
    host_prod + "101internet.ru/",
    host_prod + "101internet.ru/orders/tohome",
    host_prod + "101internet.ru/address",
    host_prod + "101internet.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_prod + "101internet.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_prod + "101internet.ru/dom/ul-vinokurova-d-2-str1-id30677",
    host_prod + "101internet.ru/doma-nzl?house_id=135510",
    host_prod + "101internet.ru/reviews",
    host_prod + "101internet.ru/rating/mts",
    host_prod + "101internet.ru/feedback",
    host_prod + "101internet.ru/rating",
    host_prod + "101internet.ru/providers",
    host_prod + "101internet.ru/providers/dom-ru",
    host_prod + "101internet.ru/providers/dom-ru/rates",
    host_prod + "101internet.ru/providers/dom-ru/rates/domashnij-internet",
    host_prod + "101internet.ru/providers/dom-ru/rates/internet-i-tv",
    host_prod + "101internet.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_prod + "101internet.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_prod + "101internet.ru/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_prod + "101internet.ru/rates",
    host_prod + "101internet.ru/rates/domashnij-internet",
    host_prod + "101internet.ru/rates/internet-i-tv",
    host_prod + "101internet.ru/rates/internet-tv-mobile",
    host_prod + "101internet.ru/rates/internet-i-mobilnaya-svyaz",
    host_prod + "101internet.ru/rates/nedorogoj-domashnij-internet",
    host_prod + "101internet.ru/rates/internet-100-mbit",
    host_prod + "101internet.ru/rates/internet-300-mbit",
    host_prod + "101internet.ru/rates/internet-500-mbit",
    host_prod + "101internet.ru/orders/sat",
    host_prod + "101internet.ru/orders/office",
    host_prod + "101internet.ru/all-districts",
    host_prod + "101internet.ru/site-map",
    host_prod + "101internet.ru/about/personal-data",
    host_prod + "101internet.ru/about/documents",
    host_prod + "101internet.ru/about/partners",
    host_prod + "101internet.ru/about/company",
    host_prod + "101internet.ru/about/contacts",
    host_prod + "101internet.ru/about/oplata-i-garantii",
    host_prod + "101internet.ru/select-region",
    host_prod + "101internet.ru/providers/dom-ru/rates/internet-100-mbit",
    host_prod + "101internet.ru/providers/dom-ru/rates/internet-300-mbit",
    host_prod + "101internet.ru/providers/dom-ru/rates/internet-500-mbit",
    host_prod + "101internet.ru/providers/actions/mts",
    host_prod + "101internet.ru/providers/dom-ru/rates/online-kinoteatr",
    host_prod + "101internet.ru/rates/online-kinoteatr",
    host_prod + "101internet.ru/actions",
    host_prod + "101internet.ru/business",
    host_prod + "101internet.ru/contact-feedback"
]