from config import host_stage, host_prod

urls = [
    host_stage + "101internet.ru/",
    host_stage + "101internet.ru/leningradskaya-oblast/nalichie-provayderov-po-adresu",
    host_stage + "101internet.ru/select-region",
    host_stage + "101internet.ru/leningradskaya-oblast",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-wifi",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-1gbitt",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-optovolokno",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-internet-tv",
    host_stage + "101internet.ru/krasnodar/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage + "101internet.ru/leningradskaya-oblast/orders/tohome",
    host_stage + "101internet.ru/gorod-tolyatti-id639/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-cherepovets-id126/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-novorossiisk-id323/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-yablonovskii-id1393/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-volgodonsk-id610/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-stariioskol-id64/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-berezniki-id568/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-severodvinsk-id30/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-novokuznetsk-id275/poisk-po-adresu",
    host_stage + "101internet.ru/gorod-angarsk-id208/poisk-po-adresu",
    host_stage + "101internet.ru/orders/tohome",
    host_stage + "101internet.ru/leningradskaya-oblast/address",
    host_stage + "101internet.ru/leningradskaya-oblast/address/%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B3-id380",
    host_stage + "101internet.ru/leningradskaya-oblast/address/%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B3-id380/%D0%BF%D0%B5%D1%80-%D0%B5%D0%BB%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BB%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-id367078",
    host_stage + "101internet.ru/leningradskaya-oblast/doma-nzl?house_id=4270758",
    host_stage + "101internet.ru/status-zayavki",
    host_stage + "101internet.ru/leningradskaya-oblast/all-districts",
    host_stage + "101internet.ru/leningradskaya-oblast/site-map",
    host_stage + "101internet.ru/all-regions",
    host_stage + "101internet.ru/leningradskaya-oblast/rating",
    host_stage + "101internet.ru/krasnodar/rating?tag=prov_goda#tags",
    host_stage + "101internet.ru/krasnodar/rating?tag=kachestvo#tags",
    host_stage + "101internet.ru/krasnodar/rating?tag=price#tags",
    host_stage + "101internet.ru/krasnodar/rating?tag=support#tags",
    host_stage + "101internet.ru/gorod-tolyatti-id639/reiting",
    host_stage + "101internet.ru/gorod-cherepovets-id126/reiting",
    host_stage + "101internet.ru/gorod-novorossiisk-id323/reiting",
    host_stage + "101internet.ru/gorod-yablonovskii-id1393/reiting",
    host_stage + "101internet.ru/gorod-volgodonsk-id610/reiting",
    host_stage + "101internet.ru/gorod-stariioskol-id64/reiting",
    host_stage + "101internet.ru/gorod-berezniki-id568/reiting",
    host_stage + "101internet.ru/gorod-severodvinsk-id30/reiting",
    host_stage + "101internet.ru/gorod-novokuznetsk-id275/reiting",
    host_stage + "101internet.ru/gorod-angarsk-id208/reiting",
    host_stage + "101internet.ru/leningradskaya-oblast/reviews",
    host_stage + "101internet.ru/leningradskaya-oblast/rating/mts",
    host_stage + "101internet.ru/leningradskaya-oblast/feedback",
    host_stage + "101internet.ru/leningradskaya-oblast/providers",
    host_stage + "101internet.ru/providers",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/dom-ru",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/yota",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates/domashnij-internet",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates/internet-i-tv",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    host_stage + "101internet.ru/leningradskaya-oblast/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    host_stage + "101internet.ru/leningradskaya-oblast/rates",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/domashnij-internet",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-i-tv",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-tv-mobile",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-i-mobilnaya-svyaz",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/nedorogoj-domashnij-internet",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-100-mbit",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-300-mbit",
    host_stage + "101internet.ru/leningradskaya-oblast/rates/internet-500-mbit",
    host_stage + "101internet.ru/chelyabinsk/rates/wifi",
    host_stage + "101internet.ru/chelyabinsk/rates/skorostnoj-internet",
    host_stage + "101internet.ru/chelyabinsk/rates/gaming",
    host_stage + "101internet.ru/chelyabinsk/rates/optovolokno",
    host_stage + "101internet.ru/chelyabinsk/rates/1gbit",
    host_stage + "101internet.ru/chelyabinsk/rates/provodnoj-internet",
    host_stage + "101internet.ru/rates",
    host_stage + "101internet.ru/leningradskaya-oblast/orders/office",
    host_stage + "101internet.ru/leningradskaya-oblast/orders/sat",
    host_stage + "101internet.ru/about/partners",
    host_stage + "101internet.ru/about/company",
    host_stage + "101internet.ru/about/oplata-i-garantii",
    host_stage + "101internet.ru/about/contacts",
    host_stage + "101internet.ru/about/documents",
    host_stage + "101internet.ru/about/personal-data",
    host_stage + "101internet.ru/articles",
    host_stage + "101internet.ru/articles/kakoj-router-vybrat",
    host_stage + "101internet.ru/experts",
    host_stage + "101internet.ru/experts/alisa-zhukova-id6",
    host_stage + "101internet.ru/help",
    host_stage + "101internet.ru/help/section-domashnij-internet",
    host_stage + "101internet.ru/help/kak-vybrat-podhodyashchij-internet-tarif",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/mts",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/mts/ratesmobile#tags#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/dlja-modema#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/vygodnye#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/semeinye#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/detskie#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/po-rossii#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/esim#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/perenos_nomera#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/bez-abonentskoj-platy#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-modema",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-noutbuka",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/bezlimitnyj-internet",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/vygodnye",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/bez-abonentskoj-platy",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/semeinye",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/detskie",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/mezhdunarodnye",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/po-rossii",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/esim",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/perenos_nomera",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/bezlimitnaja-svjaz",
    host_stage + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-plansheta",
    host_stage + "101internet.ru/leningradskaya-oblast/operatory/mts/nomera",
    host_stage + "101internet.ru/leningradskaya-oblast/nomera",
    host_stage + "101internet.ru/krasnodar/operatory/reviews",
    host_stage + "101internet.ru/krasnodar/operatory/mts/reviews",
    host_stage + "101internet.ru/krasnodar/feedback-operatory"
]

names = [
    "Главная без региона",
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Поиск по адресу для г. Тольятти",
    "Поиск по адресу для г. Череповец",
    "Поиск по адресу для г. Новороссийск",
    "Поиск по адресу для пгт. Яблоновский",
    "Поиск по адресу для г. Волгодонск",
    "Поиск по адресу для г. Старый Оскол",
    "Поиск по адресу для г. Березники",
    "Поиск по адресу для г. Северодвинск",
    "Поиск по адресу для г. Новокузнецк",
    "Поиск по адресу для г. Ангарск",
    "Поиск по адресу без региона",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Рейтинг для г. Тольятти",
    "Рейтинг для г. Череповец",
    "Рейтинг для г. Новороссийск",
    "Рейтинг для пгт. Яблоновский",
    "Рейтинг для г. Волгодонск",
    "Рейтинг для г. Старый Оскол",
    "Рейтинг для г. Березники",
    "Рейтинг для г. Северодвинск",
    "Рейтинг для г. Новокузнецк",
    "Рейтинг для г. Ангарск",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Каталог провайдеров без региона",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Тарифы провайдеров без региона",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора, тег Для модема/роутера",
    "Тарифы оператора, тег Для ноутбука",
    "Тарифы оператора, тег Безлимитные",
    "Тарифы оператора, тег Дешёвые",
    "Тарифы оператора, тег Семейные",
    "Тарифы оператора, тег Детские",
    "Тарифы оператора, тег Связь по России",
    "Тарифы оператора, тег eSIM",
    "Тарифы оператора, тег Перейти со своим номером",
    "Тарифы оператора, тег Без абонентской платы",
    "Тарифы оператора, тег Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Без абонентской платы",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Тарифы операторов в регионе, тег Безлимитная связь",
    "Тарифы операторов в регионе, тег Для планшета",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе"
]

urls_prod = [
    host_prod + "101internet.ru/",
    host_prod + "101internet.ru/leningradskaya-oblast/nalichie-provayderov-po-adresu",
    host_prod + "101internet.ru/select-region",
    host_prod + "101internet.ru/leningradskaya-oblast",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-wifi",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-deshevyj-internet",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-1gbitt",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-provodnoj-internet",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-optovolokno",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/podklyuchit-internet-tv",
    host_prod + "101internet.ru/krasnodar/domashniy-internet/besplatnoe-podklyuchenie",
    host_prod + "101internet.ru/leningradskaya-oblast/orders/tohome",
    host_prod + "101internet.ru/gorod-tolyatti-id639/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-cherepovets-id126/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-novorossiisk-id323/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-yablonovskii-id1393/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-volgodonsk-id610/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-stariioskol-id64/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-berezniki-id568/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-severodvinsk-id30/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-novokuznetsk-id275/poisk-po-adresu",
    host_prod + "101internet.ru/gorod-angarsk-id208/poisk-po-adresu",
    host_prod + "101internet.ru/orders/tohome",
    host_prod + "101internet.ru/leningradskaya-oblast/address",
    host_prod + "101internet.ru/leningradskaya-oblast/address/%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B3-id380",
    host_prod + "101internet.ru/leningradskaya-oblast/address/%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B3-id380/%D0%BF%D0%B5%D1%80-%D0%B5%D0%BB%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BB%D0%B5%D0%BD%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-id367078",
    host_prod + "101internet.ru/leningradskaya-oblast/doma-nzl?house_id=4270758",
    host_prod + "101internet.ru/status-zayavki",
    host_prod + "101internet.ru/leningradskaya-oblast/all-districts",
    host_prod + "101internet.ru/leningradskaya-oblast/site-map",
    host_prod + "101internet.ru/leningradskaya-oblast/all-regions",
    host_prod + "101internet.ru/leningradskaya-oblast/rating",
    host_prod + "101internet.ru/krasnodar/rating?tag=prov_goda#tags",
    host_prod + "101internet.ru/krasnodar/rating?tag=kachestvo#tags",
    host_prod + "101internet.ru/krasnodar/rating?tag=price#tags",
    host_prod + "101internet.ru/krasnodar/rating?tag=support#tags",
    host_prod + "101internet.ru/gorod-tolyatti-id639/reiting",
    host_prod + "101internet.ru/gorod-cherepovets-id126/reiting",
    host_prod + "101internet.ru/gorod-novorossiisk-id323/reiting",
    host_prod + "101internet.ru/gorod-yablonovskii-id1393/reiting",
    host_prod + "101internet.ru/gorod-volgodonsk-id610/reiting",
    host_prod + "101internet.ru/gorod-stariioskol-id64/reiting",
    host_prod + "101internet.ru/gorod-berezniki-id568/reiting",
    host_prod + "101internet.ru/gorod-severodvinsk-id30/reiting",
    host_prod + "101internet.ru/gorod-novokuznetsk-id275/reiting",
    host_prod + "101internet.ru/gorod-angarsk-id208/reiting",
    host_prod + "101internet.ru/leningradskaya-oblast/reviews",
    host_prod + "101internet.ru/leningradskaya-oblast/rating/mts",
    host_prod + "101internet.ru/leningradskaya-oblast/feedback",
    host_prod + "101internet.ru/leningradskaya-oblast/providers",
    host_prod + "101internet.ru/providers",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/dom-ru",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/awanti",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates/domashnij-internet",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates/internet-i-tv",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/rostelecom/rates/internet-tv-mobile",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    host_prod + "101internet.ru/leningradskaya-oblast/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_prod + "101internet.ru/leningradskaya-oblast/rates",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/domashnij-internet",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-i-tv",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-tv-mobile",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-i-mobilnaya-svyaz",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/nedorogoj-domashnij-internet",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-100-mbit",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-300-mbit",
    host_prod + "101internet.ru/leningradskaya-oblast/rates/internet-500-mbit",
    host_prod + "101internet.ru/chelyabinsk/rates/wifi",
    host_prod + "101internet.ru/chelyabinsk/rates/skorostnoj-internet",
    host_prod + "101internet.ru/chelyabinsk/rates/gaming",
    host_prod + "101internet.ru/chelyabinsk/rates/optovolokno",
    host_prod + "101internet.ru/chelyabinsk/rates/1gbit",
    host_prod + "101internet.ru/chelyabinsk/rates/provodnoj-internet",
    host_prod + "101internet.ru/rates",
    host_prod + "101internet.ru/leningradskaya-oblast/orders/office",
    host_prod + "101internet.ru/leningradskaya-oblast/orders/sat",
    host_prod + "101internet.ru/about/partners",
    host_prod + "101internet.ru/about/company",
    host_prod + "101internet.ru/about/oplata-i-garantii",
    host_prod + "101internet.ru/about/contacts",
    host_prod + "101internet.ru/about/documents",
    host_prod + "101internet.ru/about/personal-data",
    host_prod + "101internet.ru/articles",
    host_prod + "101internet.ru/articles/luchshaya-simkarta-dlya-interneta",
    host_prod + "101internet.ru/experts",
    host_prod + "101internet.ru/experts/alisa-zhukova-id7",
    host_prod + "101internet.ru/help",
    host_prod + "101internet.ru/help/section-domashnij-internet",
    host_prod + "101internet.ru/help/kak-vybrat-podhodyashchij-internet-tarif",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/mts",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/mts/ratesmobile#tags#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/dlja-modema#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/vygodnye#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/semeinye#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/detskie#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/po-rossii#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/esim#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/perenos_nomera#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/beeline/ratesmobile/bez-abonentskoj-platy#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-modema",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-noutbuka",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/bezlimitnyj-internet",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/vygodnye",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/bez-abonentskoj-platy",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/semeinye",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/detskie",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/mezhdunarodnye",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/po-rossii",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/esim",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/perenos_nomera",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/bezlimitnaja-svjaz",
    host_prod + "101internet.ru/leningradskaya-oblast/ratesmobile/dlja-plansheta",
    host_prod + "101internet.ru/leningradskaya-oblast/operatory/mts/nomera",
    host_prod + "101internet.ru/leningradskaya-oblast/nomera",
    host_prod + "101internet.ru/krasnodar/operatory/reviews",
    host_prod + "101internet.ru/krasnodar/operatory/mts/reviews",
    host_prod + "101internet.ru/krasnodar/feedback-operatory"
]

names_stage = [
    "Главная без региона",
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Поиск по адресу для г. Тольятти",
    "Поиск по адресу для г. Череповец",
    "Поиск по адресу для г. Новороссийск",
    "Поиск по адресу для пгт. Яблоновский",
    "Поиск по адресу для г. Волгодонск",
    "Поиск по адресу для г. Старый Оскол",
    "Поиск по адресу для г. Березники",
    "Поиск по адресу для г. Северодвинск",
    "Поиск по адресу для г. Новокузнецк",
    "Поиск по адресу для г. Ангарск",
    "Поиск по адресу без региона",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Рейтинг для г. Тольятти",
    "Рейтинг для г. Череповец",
    "Рейтинг для г. Новороссийск",
    "Рейтинг для пгт. Яблоновский",
    "Рейтинг для г. Волгодонск",
    "Рейтинг для г. Старый Оскол",
    "Рейтинг для г. Березники",
    "Рейтинг для г. Северодвинск",
    "Рейтинг для г. Новокузнецк",
    "Рейтинг для г. Ангарск",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Каталог провайдеров без региона",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Тарифы провайдеров без региона",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора, тег Для модема/роутера",
    "Тарифы оператора, тег Для ноутбука",
    "Тарифы оператора, тег Безлимитные",
    "Тарифы оператора, тег Дешёвые",
    "Тарифы оператора, тег Семейные",
    "Тарифы оператора, тег Детские",
    "Тарифы оператора, тег Связь по России",
    "Тарифы оператора, тег eSIM",
    "Тарифы оператора, тег Перейти со своим номером",
    "Тарифы оператора, тег Без абонентской платы",
    "Тарифы оператора, тег Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Без абонентской платы",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Тарифы операторов в регионе, тег Безлимитная связь",
    "Тарифы операторов в регионе, тег Для планшета",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе"
]
