from config import host_stage

urls = [
    "https://piter-online.net/nalichie-provayderov-po-adresu",
    "https://piter-online.net/select-region",
    "https://piter-online.net/leningradskaya-oblast",
    "https://piter-online.net/domashniy-internet/podklyuchit-wifi",
    "https://piter-online.net/domashniy-internet/podklyuchit-skorostnoj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-deshevyj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-1gbit",
    "https://piter-online.net/domashniy-internet/podklyuchit-provodnoj-internet",
    "https://piter-online.net/domashniy-internet/podklyuchit-optovolokno",
    "https://piter-online.net/domashniy-internet/podklyuchit-internet-tv",
    "https://piter-online.net/domashniy-internet/besplatnoe-podklyuchenie",
    "https://piter-online.net/orders/tohome",
    "https://piter-online.net/address",
    "https://piter-online.net/pavlovsk-id1250",
    "https://piter-online.net/ulicy/internet-provaydery-ul-2-yakrasnoflotskaya-id295159",
    "https://piter-online.net/leningradskaya-oblast/doma-nzl?house_id=4270758",
    "https://piter-online.net/status-zayavki",
    "https://piter-online.net/all-districts",
    "https://piter-online.net/leningradskaya-oblast/site-map",
    "https://piter-online.net/all-regions",
    "https://piter-online.net/rating",
    "https://piter-online.net/rating?tag=prov_goda#tags",
    "https://piter-online.net/rating?tag=kachestvo#tags",
    "https://piter-online.net/rating?tag=price#tags",
    "https://piter-online.net/rating?tag=support#tags",
    "https://piter-online.net/reviews",
    "https://piter-online.net/rating/mts",
    "https://piter-online.net/feedback",
    "https://piter-online.net/providers",
    "https://piter-online.net/providers/dom-ru",
    "https://piter-online.net/providers/awanti",
    "https://piter-online.net/providers/dom-ru/rates",
    "https://piter-online.net/providers/dom-ru/rates/domashnij-internet",
    "https://piter-online.net/providers/dom-ru/rates/internet-i-tv",
    "https://piter-online.net/providers/rostelecom/rates/internet-tv-mobile",
    "https://piter-online.net/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rates",
    "https://piter-online.net/rates/domashnij-internet",
    "https://piter-online.net/rates/internet-i-tv",
    "https://piter-online.net/rates/internet-tv-mobile",
    "https://piter-online.net/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rates/internet-100-mbit",
    "https://piter-online.net/rates/internet-300-mbit",
    "https://piter-online.net/rates/internet-500-mbit",
    "https://piter-online.net/rates/wifi",
    "https://piter-online.net/rates/skorostnoj-internet",
    "https://piter-online.net/leningradskaya-oblast/rates/gaming",
    "https://piter-online.net/leningradskaya-oblast/rates/optovolokno",
    "https://piter-online.net/rates/1gbit",
    "https://piter-online.net/rates/provodnoj-internett",
    "https://piter-online.net/orders/office",
    "https://piter-online.net/orders/sat",
    "https://piter-online.net/about/partners",
    "https://piter-online.net/about/company",
    "https://piter-online.net/about/oplata-i-garantii",
    "https://piter-online.net/about/contacts",
    "https://piter-online.net/about/documents",
    "https://piter-online.net/about/personal-data",
    "https://piter-online.net/about/otzyvy-o-nas",
    "https://piter-online.net/articles",
    "https://piter-online.net/articles/luchshaya-simkarta-dlya-interneta",
    "https://piter-online.net/experts",
    "https://piter-online.net/experts/alisa-zhukova-id7",
    "https://piter-online.net/help",
    "https://piter-online.net/help/section-domashnij-internet",
    "https://piter-online.net/help/kak-vybrat-luchshij-internet-tarif",
    "https://piter-online.net/operatory",
    "https://piter-online.net/operatory/mts",
    "https://piter-online.net/operatory/mts/ratesmobile#tags",
    "https://piter-online.net/operatory/tele-2/ratesmobile/dlja-modema#tags ",
    "https://piter-online.net/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    "https://piter-online.net/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    "https://piter-online.net/operatory/tele-2/ratesmobile/vygodnye#tags",
    "https://piter-online.net/operatory/beeline/ratesmobile/semeinye#tags",
    "https://piter-online.net/operatory/beeline/ratesmobile/detskie#tags",
    "https://piter-online.net/operatory/tele-2/ratesmobile/po-rossii#tags",
    "https://piter-online.net/operatory/mts/ratesmobile/esim#tags",
    "https://piter-online.net/operatory/mts/ratesmobile/perenos_nomera#tags",
    "https://piter-online.net/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    "https://piter-online.net/ratesmobile",
    "https://piter-online.net/ratesmobile/dlja-modema",
    "https://piter-online.net/ratesmobile/dlja-noutbuka",
    "https://piter-online.net/ratesmobile/bezlimitnyj-internet",
    "https://piter-online.net/ratesmobile/vygodnye",
    "https://piter-online.net/ratesmobile/semeinye",
    "https://piter-online.net/ratesmobile/detskie",
    "https://piter-online.net/ratesmobile/mezhdunarodnye",
    "https://piter-online.net/ratesmobile/po-rossii",
    "https://piter-online.net/ratesmobile/esim",
    "https://piter-online.net/ratesmobile/perenos_nomera",
    "https://piter-online.net/operatory/mts/nomera",
    "https://piter-online.net/nomera",
    "https://piter-online.net/operatory/reviews",
    "https://piter-online.net/operatory/mts/reviews",
    "https://piter-online.net/feedback-operatory"
]

names = [
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Отзывы о нас",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора с тегом Для модема/роутера",
    "Тарифы оператора с тегом Для ноутбука",
    "Тарифы оператора с тегом Безлимитные",
    "Тарифы оператора с тегом Дешёвые",
    "Тарифы оператора с тегом Семейные",
    "Тарифы оператора с тегом Детские",
    "Тарифы оператора с тегом Связь по России",
    "Тарифы оператора с тегом eSIM",
    "Тарифы оператора с тегом Перейти со своим номером",
    "Тарифы оператора с тегом Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе"
]

urls_stage = [
    host_stage + "piter-online.net/nalichie-provayderov-po-adresu",
    host_stage + "piter-online.net/select-region",
    host_stage + "piter-online.net/leningradskaya-oblast",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-wifi",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-1gbit",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-optovolokno",
    host_stage + "piter-online.net/domashniy-internet/podklyuchit-internet-tv",
    host_stage + "piter-online.net/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage + "piter-online.net/orders/tohome",
    host_stage + "piter-online.net/address",
    host_stage + "piter-online.net/krasnoeselo-id1450",
    host_stage + "piter-online.net/ulicy/internet-provaydery-pr-kt-lenina-id294226",
    host_stage + "piter-online.net/leningradskaya-oblast/doma-nzl?house_id=4270758",
    host_stage + "piter-online.net/status-zayavki",
    host_stage + "piter-online.net/all-districts",
    host_stage + "piter-online.net/leningradskaya-oblast/site-map",
    host_stage + "piter-online.net/all-regions",
    host_stage + "piter-online.net/rating",
    host_stage + "piter-online.net/rating?tag=prov_goda#tags",
    host_stage + "piter-online.net/rating?tag=kachestvo#tags",
    host_stage + "piter-online.net/rating?tag=price#tags",
    host_stage + "piter-online.net/rating?tag=support#tags",
    host_stage + "piter-online.net/reviews",
    host_stage + "piter-online.net/rating/mts",
    host_stage + "piter-online.net/feedback",
    host_stage + "piter-online.net/providers",
    host_stage + "piter-online.net/providers/dom-ru",
    host_stage + "piter-online.net/providers/awanti",
    host_stage + "piter-online.net/providers/dom-ru/rates",
    host_stage + "piter-online.net/providers/dom-ru/rates/domashnij-internet",
    host_stage + "piter-online.net/providers/dom-ru/rates/internet-i-tv",
    host_stage + "piter-online.net/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "piter-online.net/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rates",
    host_stage + "piter-online.net/rates/domashnij-internet",
    host_stage + "piter-online.net/rates/internet-i-tv",
    host_stage + "piter-online.net/rates/internet-tv-mobile",
    host_stage + "piter-online.net/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rates/internet-100-mbit",
    host_stage + "piter-online.net/rates/internet-300-mbit",
    host_stage + "piter-online.net/rates/internet-500-mbit",
    host_stage + "piter-online.net/rates/wifi",
    host_stage + "piter-online.net/rates/skorostnoj-internet",
    host_stage + "piter-online.net/leningradskaya-oblast/rates/gaming",
    host_stage + "piter-online.net/leningradskaya-oblast/rates/optovolokno",
    host_stage + "piter-online.net/leningradskaya-oblast/rates/1gbit",
    host_stage + "piter-online.net/rates/provodnoj-internet",
    host_stage + "piter-online.net/orders/office",
    host_stage + "piter-online.net/orders/sat",
    host_stage + "piter-online.net/about/partners",
    host_stage + "piter-online.net/about/company",
    host_stage + "piter-online.net/about/oplata-i-garantii",
    host_stage + "piter-online.net/about/contacts",
    host_stage + "piter-online.net/about/documents",
    host_stage + "piter-online.net/about/personal-data",
    host_stage + "piter-online.net/about/otzyvy-o-nas",
    host_stage + "piter-online.net/articles",
    host_stage + "piter-online.net/articles/luchshaya-simkarta-dlya-interneta",
    host_stage + "piter-online.net/experts",
    host_stage + "piter-online.net/experts/alisa-zhukova-id7",
    host_stage + "piter-online.net/help",
    host_stage + "piter-online.net/help/section-domashnij-internet",
    host_stage + "piter-online.net/help/kak-vybrat-luchshij-internet-tarif",
    host_stage + "piter-online.net/operatory",
    host_stage + "piter-online.net/operatory/mts",
    host_stage + "piter-online.net/operatory/mts/ratesmobile#tags",
    host_stage + "piter-online.net/operatory/tele-2/ratesmobile/dlja-modema#tags",
    host_stage + "piter-online.net/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    host_stage + "piter-online.net/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    host_stage + "piter-online.net/operatory/tele-2/ratesmobile/vygodnye#tags",
    host_stage + "piter-online.net/operatory/beeline/ratesmobile/semeinye#tags",
    host_stage + "piter-online.net/operatory/beeline/ratesmobile/detskie#tags",
    host_stage + "piter-online.net/operatory/tele-2/ratesmobile/po-rossii#tags",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/esim#tags",
    host_stage + "piter-online.net/operatory/mts/ratesmobile/perenos_nomera#tags",
    host_stage + "piter-online.net/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    host_stage + "piter-online.net/ratesmobile",
    host_stage + "piter-online.net/ratesmobile/dlja-modema",
    host_stage + "piter-online.net/ratesmobile/dlja-noutbuka",
    host_stage + "piter-online.net/ratesmobile/bezlimitnyj-internet",
    host_stage + "piter-online.net/ratesmobile/vygodnye",
    host_stage + "piter-online.net/ratesmobile/semeinye",
    host_stage + "piter-online.net/ratesmobile/detskie",
    host_stage + "piter-online.net/ratesmobile/mezhdunarodnye",
    host_stage + "piter-online.net/ratesmobile/po-rossii",
    host_stage + "piter-online.net/ratesmobile/esim",
    host_stage + "piter-online.net/ratesmobile/perenos_nomera",
    host_stage + "piter-online.net/operatory/mts/nomera",
    host_stage + "piter-online.net/nomera",
    host_stage + "piter-online.net/operatory/reviews",
    host_stage + "piter-online.net/operatory/mts/reviews",
    host_stage + "piter-online.net/feedback-operatory"
]

names_stage = [
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Отзывы о нас",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора с тегом Для модема/роутера",
    "Тарифы оператора с тегом Для ноутбука",
    "Тарифы оператора с тегом Безлимитные",
    "Тарифы оператора с тегом Дешёвые",
    "Тарифы оператора с тегом Семейные",
    "Тарифы оператора с тегом Детские",
    "Тарифы оператора с тегом Связь по России",
    "Тарифы оператора с тегом eSIM",
    "Тарифы оператора с тегом Перейти со своим номером",
    "Тарифы оператора с тегом Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе"
]
