from config import host_stage

urls = [
    "https://piter-online.net/",
    "https://piter-online.net/orders/tohome",
    "https://piter-online.net/address",
    "https://piter-online.net/address/%D0%BF%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D1%81%D0%BA-id1250",
    "https://piter-online.net/address/%D0%BF%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D1%81%D0%BA-id1250/%D1%83%D0%BB-2-%D1%8F-%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D1%84%D0%BB%D0%BE%D1%82%D1%81%D0%BA%D0%B0%D1%8F-id295159",
    "https://piter-online.net/dom/ul-2-yakrasnoflotskaya-d-6-k2a-id1018691",
    "https://piter-online.net/leningradskaya-oblast/doma-nzl?house_id=4270758",
    "https://piter-online.net/all-districts",
    "https://piter-online.net/rating",
    "https://piter-online.net/reviews",
    "https://piter-online.net/rating/mts",
    "https://piter-online.net/feedback",
    "https://piter-online.net/providers",
    "https://piter-online.net/providers/dom-ru",
    "https://piter-online.net/providers/rostelecom",
    "https://piter-online.net/providers/tele-2",
    "https://piter-online.net/providers/mts",
    "https://piter-online.net/providers/megafon",
    "https://piter-online.net/providers/beeline",
    "https://piter-online.net/providers/akado-neva",
    "https://piter-online.net/providers/awanti",
    "https://piter-online.net/providers/dom-ru/rates",
    "https://piter-online.net/providers/rostelecom/rates",
    "https://piter-online.net/providers/tele-2/rates",
    "https://piter-online.net/providers/mts/rates",
    "https://piter-online.net/providers/megafon/rates",
    "https://piter-online.net/providers/beeline/rates",
    "https://piter-online.net/providers/akado-neva/rates",
    "https://piter-online.net/providers/dom-ru/rates/domashnij-internet",
    "https://piter-online.net/providers/rostelecom/rates/domashnij-internet",
    "https://piter-online.net/providers/tele-2/rates/domashnij-internet",
    "https://piter-online.net/providers/mts/rates/domashnij-internet",
    "https://piter-online.net/providers/megafon/rates/domashnij-internet",
    "https://piter-online.net/providers/beeline/rates/domashnij-internet",
    "https://piter-online.net/providers/akado-neva/rates/domashnij-internet",
    "https://piter-online.net/providers/dom-ru/rates/internet-i-tv",
    "https://piter-online.net/providers/rostelecom/rates/internet-i-tv",
    "https://piter-online.net/providers/beeline/rates/internet-i-tv",
    "https://piter-online.net/providers/akado-neva/rates/internet-i-tv",
    "https://piter-online.net/providers/rostelecom/rates/internet-tv-mobile",
    "https://piter-online.net/providers/tele-2/rates/internet-tv-mobile",
    "https://piter-online.net/providers/mts/rates/internet-tv-mobile",
    "https://piter-online.net/providers/megafon/rates/internet-tv-mobile",
    "https://piter-online.net/providers/beeline/rates/internet-tv-mobile",
    "https://piter-online.net/providers/wifire/rates/internet-tv-mobile",
    "https://piter-online.net/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/tele-2/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/mts/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/megafon/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/wifire/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/tele-2/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/mts/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/megafon/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/beeline/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/providers/wifire/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rates",
    "https://piter-online.net/rates/domashnij-internet",
    "https://piter-online.net/rates/internet-i-tv",
    "https://piter-online.net/rates/internet-tv-mobile",
    "https://piter-online.net/rates/internet-i-mobilnaya-svyaz",
    "https://piter-online.net/rates/nedorogoj-domashnij-internet",
    "https://piter-online.net/rates/internet-100-mbit",
    "https://piter-online.net/rates/internet-300-mbit",
    "https://piter-online.net/rates/internet-500-mbit",
    "https://piter-online.net/orders/office",
    "https://piter-online.net/orders/sat",
    "https://piter-online.net/about/partners",
    "https://piter-online.net/about/company",
    "https://piter-online.net/about/contacts",
    "https://piter-online.net/about/oplata-i-garantii"
]

names = [
    "Главная",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Золотой дом",
    "Обычный дом",
    "Все районы",
    "Рейтинг",
    "Отзывы в регионе",
    "Отзывы провайдера",
    "Страница оставления отзыва",
    "Каталог",
    "Страница провайдера Домру",
    "Страница провайдера Ростелеком",
    "Страница провайдера Теле2",
    "Страница провайдера МТС",
    "Страница провайдера Мегафон",
    "Страница провайдера Билайн",
    "Страница провайдера Вип пров",
    "Страница провайдера Невип пров",
    "Тарифы провайдера (тег Все) Домру",
    "Тарифы провайдера (тег Все) Ростелеком",
    "Тарифы провайдера (тег Все) Теле2",
    "Тарифы провайдера (тег Все) МТС",
    "Тарифы провайдера (тег Все) Мегафон",
    "Тарифы провайдера (тег Все) Билайн",
    "Тарифы провайдера (тег Все) Вип пров",
    "Тарифы провайдера, тег Домашний интернет Домру",
    "Тарифы провайдера, тег Домашний интернет Ростелеком",
    "Тарифы провайдера, тег Домашний интернет Теле2",
    "Тарифы провайдера, тег Домашний интернет МТС",
    "Тарифы провайдера, тег Домашний интернет Мегафон",
    "Тарифы провайдера, тег Домашний интернет Билайн",
    "Тарифы провайдера, тег Домашний интернет Вип пров",
    "Тарифы провайдера, тег Интернет + ТВ Домру",
    "Тарифы провайдера, тег Интернет + ТВ Ростелеком",
    "Тарифы провайдера, тег Интернет + ТВ Билайн",
    "Тарифы провайдера, тег Интернет + ТВ Вип пров",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь Ростелеком",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь Теле2",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь МТС",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь Мегафон",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь Билайн",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь Вип пров",
    "Тарифы провайдера, тег Интернет + Мобильная связь Ростелеком",
    "Тарифы провайдера, тег Интернет + Мобильная связь Теле2",
    "Тарифы провайдера, тег Интернет + Мобильная связь МТС",
    "Тарифы провайдера, тег Интернет + Мобильная связь Мегафон",
    "Тарифы провайдера, тег Интернет + Мобильная связь Вип пров",
    "Тарифы провайдера, тег Акции Домру",
    "Тарифы провайдера, тег Акции Ростелеком",
    "Тарифы провайдера, тег Акции Теле2",
    "Тарифы провайдера, тег Акции МТС",
    "Тарифы провайдера, тег Акции Мегафон",
    "Тарифы провайдера, тег Акции Билайн",
    "Тарифы провайдера, тег Акции Вип пров",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "В офис",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Контакты",
    "Оплата и гарантии",
]


urls_stage = [
    host_stage + "piter-online.net/",
    host_stage + "piter-online.net/orders/tohome",
    host_stage + "piter-online.net/address",
    host_stage + "piter-online.net/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_stage + "piter-online.net/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_stage + "piter-online.net/dom/ul-vinokurova-d-2-str1-id30677",
    host_stage + "piter-online.net/doma-nzl?house_id=135510",
    host_stage + "piter-online.net/reviews",
    host_stage + "piter-online.net/rating/mts",
    host_stage + "piter-online.net/feedback",
    host_stage + "piter-online.net/rating",
    host_stage + "piter-online.net/providers",
    host_stage + "piter-online.net/providers/dom-ru",
    host_stage + "piter-online.net/providers/dom-ru/rates",
    host_stage + "piter-online.net/providers/dom-ru/rates/domashnij-internet",
    host_stage + "piter-online.net/providers/dom-ru/rates/internet-i-tv",
    host_stage + "piter-online.net/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "piter-online.net/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rates",
    host_stage + "piter-online.net/rates/domashnij-internet",
    host_stage + "piter-online.net/rates/internet-i-tv",
    host_stage + "piter-online.net/rates/internet-tv-mobile",
    host_stage + "piter-online.net/rates/internet-i-mobilnaya-svyaz",
    host_stage + "piter-online.net/rates/nedorogoj-domashnij-internet",
    host_stage + "piter-online.net/rates/internet-100-mbit",
    host_stage + "piter-online.net/rates/internet-300-mbit",
    host_stage + "piter-online.net/rates/internet-500-mbit",
    host_stage + "piter-online.net/orders/sat",
    host_stage + "piter-online.net/orders/office",
    host_stage + "piter-online.net/all-districts",
    host_stage + "piter-online.net/site-map",
    host_stage + "piter-online.net/about/personal-data",
    host_stage + "piter-online.net/about/documents",
    host_stage + "piter-online.net/about/partners",
    host_stage + "piter-online.net/about/company",
    host_stage + "piter-online.net/about/contacts",
    host_stage + "piter-online.net/about/oplata-i-garantii",
    host_stage + "piter-online.net/select-region",
    host_stage + "piter-online.net/providers/dom-ru/rates/internet-100-mbit",
    host_stage + "piter-online.net/providers/dom-ru/rates/internet-300-mbit",
    host_stage + "piter-online.net/providers/dom-ru/rates/internet-500-mbit",
    host_stage + "piter-online.net/providers/actions/mts",
    host_stage + "piter-online.net/providers/dom-ru/rates/online-kinoteatr",
    host_stage + "piter-online.net/rates/online-kinoteatr",
    host_stage + "piter-online.net/actions",
    host_stage + "piter-online.net/business",
    host_stage + "piter-online.net/contact-feedback"
]