from config import host_stage, host_prod

urls = [
    host_stage + "moskvaonline.ru/nalichie-provayderov-po-adresu",
    host_stage + "moskvaonline.ru/select-region",
    host_stage + "moskvaonline.ru/moskovskaya-oblast",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-wifi",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-deshevyj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-1gbit",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-provodnoj-internet",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-optovolokno",
    host_stage + "moskvaonline.ru/domashniy-internet/podklyuchit-internet-tv",
    host_stage + "moskvaonline.ru/domashniy-internet/besplatnoe-podklyuchenie",
    host_stage + "moskvaonline.ru/orders/tohome",
    host_stage + "moskvaonline.ru/address",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_stage + "moskvaonline.ru/doma-nzl?house_id=3074381",
    host_stage + "moskvaonline.ru/status-zayavki",
    host_stage + "moskvaonline.ru/all-districts",
    host_stage + "moskvaonline.ru/moskovskaya-oblast/site-map",
    host_stage + "moskvaonline.ru/all-regions",
    host_stage + "moskvaonline.ru/rating",
    host_stage + "moskvaonline.ru/rating?tag=prov_goda#tags",
    host_stage + "moskvaonline.ru/rating?tag=kachestvo#tags",
    host_stage + "moskvaonline.ru/rating?tag=price#tags",
    host_stage + "moskvaonline.ru/rating?tag=support#tags",
    host_stage + "moskvaonline.ru/reviews",
    host_stage + "moskvaonline.ru/rating/mts",
    host_stage + "moskvaonline.ru/feedback",
    host_stage + "moskvaonline.ru/providers",
    host_stage + "moskvaonline.ru/providers/dom-ru",
    host_stage + "moskvaonline.ru/providers/avk",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/domashnij-internet",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rates",
    host_stage + "moskvaonline.ru/rates/domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-100-mbit",
    host_stage + "moskvaonline.ru/rates/internet-300-mbit",
    host_stage + "moskvaonline.ru/rates/internet-500-mbit",
    host_stage + "moskvaonline.ru/moskovskaya-oblast/rates/wifi",
    host_stage + "moskvaonline.ru/rates/skorostnoj-internet",
    host_stage + "moskvaonline.ru/moskovskaya-oblast/rates/gaming",
    host_stage + "moskvaonline.ru/moskovskaya-oblast/rates/optovolokno",
    host_stage + "moskvaonline.ru/rates/1gbit",
    host_stage + "moskvaonline.ru/moskovskaya-oblast/rates/provodnoj-internet",
    host_stage + "moskvaonline.ru/orders/office",
    host_stage + "moskvaonline.ru/orders/sat",
    host_stage + "moskvaonline.ru/about/partners",
    host_stage + "moskvaonline.ru/about/company",
    host_stage + "moskvaonline.ru/about/oplata-i-garantii",
    host_stage + "moskvaonline.ru/about/contacts",
    host_stage + "moskvaonline.ru/about/documents",
    host_stage + "moskvaonline.ru/about/personal-data",
    host_stage + "moskvaonline.ru/about/otzyvy-o-nas",
    host_stage + "moskvaonline.ru/articles",
    host_stage + "moskvaonline.ru/articles/chem-otlichayutsya-routery",
    host_stage + "moskvaonline.ru/experts",
    host_stage + "moskvaonline.ru/experts/alisa-zhukova-id8",
    host_stage + "moskvaonline.ru/help",
    host_stage + "moskvaonline.ru/help/section-first",
    host_stage + "moskvaonline.ru/help/kak-podklyuchit-provodnoj-internet",
    host_stage + "moskvaonline.ru/operatory",
    host_stage + "moskvaonline.ru/operatory/mts",
    host_stage + "moskvaonline.ru/operatory/mts/ratesmobile#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/dlja-modema#tags",
    host_stage + "moskvaonline.ru/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/vygodnye#tags",
    host_stage + "moskvaonline.ru/operatory/beeline/ratesmobile/semeinye#tags",
    host_stage + "moskvaonline.ru/operatory/beeline/ratesmobile/detskie#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/po-rossii#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/esim#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/perenos_nomera#tags",
    host_stage + "moskvaonline.ru/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    host_stage + "moskvaonline.ru/ratesmobile",
    host_stage + "moskvaonline.ru/ratesmobile/dlja-modema",
    host_stage + "moskvaonline.ru/ratesmobile/dlja-noutbuka",
    host_stage + "moskvaonline.ru/ratesmobile/bezlimitnyj-internet",
    host_stage + "moskvaonline.ru/ratesmobile/vygodnye",
    host_stage + "moskvaonline.ru/ratesmobile/semeinye",
    host_stage + "moskvaonline.ru/ratesmobile/detskie",
    host_stage + "moskvaonline.ru/ratesmobile/mezhdunarodnye",
    host_stage + "moskvaonline.ru/ratesmobile/po-rossii",
    host_stage + "moskvaonline.ru/ratesmobile/esim",
    host_stage + "moskvaonline.ru/ratesmobile/perenos_nomera",
    host_stage + "moskvaonline.ru/operatory/mts/nomera",
    host_stage + "moskvaonline.ru/nomera",
    host_stage + "moskvaonline.ru/operatory/reviews",
    host_stage + "moskvaonline.ru/operatory/mts/reviews",
    host_stage + "moskvaonline.ru/feedback-operatory"
]

names = [
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора с тегом Для модема/роутера",
    "Тарифы оператора с тегом Для ноутбука",
    "Тарифы оператора с тегом Безлимитные",
    "Тарифы оператора с тегом Дешёвые",
    "Тарифы оператора с тегом Семейные",
    "Тарифы оператора с тегом Детские",
    "Тарифы оператора с тегом Связь по России",
    "Тарифы оператора с тегом eSIM",
    "Тарифы оператора с тегом Перейти со своим номером",
    "Тарифы оператора с тегом Без абонентской платы",
    "Тарифы оператора с тегом Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Без абонентской платы",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Тарифы операторов в регионе, тег Безлимитная связь",
    "Тарифы операторов в регионе, тег Для планшета",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе"
]

urls_prod = [
    host_prod + "moskvaonline.ru/nalichie-provayderov-po-adresu",
    host_prod + "moskvaonline.ru/select-region",
    host_prod + "moskvaonline.ru/moskovskaya-oblast",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-wifi",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-skorostnoj-internet",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-deshevyj-internet",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-1gbit",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-provodnoj-internet",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-optovolokno",
    host_prod + "moskvaonline.ru/domashniy-internet/podklyuchit-internet-tv",
    host_prod + "moskvaonline.ru/domashniy-internet/besplatnoe-podklyuchenie",
    host_prod + "moskvaonline.ru/orders/tohome",
    host_prod + "moskvaonline.ru/address",
    host_prod + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_prod + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_prod + "moskvaonline.ru/doma-nzl?house_id=3074381",
    host_prod + "moskvaonline.ru/status-zayavki",
    host_prod + "moskvaonline.ru/all-districts",
    host_prod + "moskvaonline.ru/site-map",
    host_prod + "moskvaonline.ru/all-regions",
    host_prod + "moskvaonline.ru/rating",
    host_prod + "moskvaonline.ru/rating?tag=prov_goda#tags",
    host_prod + "moskvaonline.ru/rating?tag=kachestvo#tags",
    host_prod + "moskvaonline.ru/rating?tag=price#tags",
    host_prod + "moskvaonline.ru/rating?tag=support#tags",
    host_prod + "moskvaonline.ru/reviews",
    host_prod + "moskvaonline.ru/rating/mts",
    host_prod + "moskvaonline.ru/feedback",
    host_prod + "moskvaonline.ru/providers",
    host_prod + "moskvaonline.ru/providers/dom-ru",
    host_prod + "moskvaonline.ru/providers/avk",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/domashnij-internet",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/internet-i-tv",
    host_prod + "moskvaonline.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_prod + "moskvaonline.ru/providers/rostelecom/rates/internet-i-mobilnaya-svyaz",
    host_prod + "moskvaonline.ru/providers/rostelecom/rates/nedorogoj-domashnij-internet",
    host_prod + "moskvaonline.ru/rates",
    host_prod + "moskvaonline.ru/rates/domashnij-internet",
    host_prod + "moskvaonline.ru/rates/internet-i-tv",
    host_prod + "moskvaonline.ru/rates/internet-tv-mobile",
    host_prod + "moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    host_prod + "moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    host_prod + "moskvaonline.ru/rates/internet-100-mbit",
    host_prod + "moskvaonline.ru/rates/internet-300-mbit",
    host_prod + "moskvaonline.ru/rates/internet-500-mbit",
    host_prod + "moskvaonline.ru/moskovskaya-oblast/rates/wifi",
    host_prod + "moskvaonline.ru/rates/skorostnoj-internett",
    host_prod + "moskvaonline.ru/moskovskaya-oblast/rates/gaming",
    host_prod + "moskvaonline.ru/moskovskaya-oblast/rates/optovolokno",
    host_prod + "moskvaonline.ru/rates/1gbitt",
    host_prod + "moskvaonline.ru/moskovskaya-oblast/rates/provodnoj-internet",
    host_prod + "moskvaonline.ru/orders/office",
    host_prod + "moskvaonline.ru/orders/sat",
    host_prod + "moskvaonline.ru/about/partners",
    host_prod + "moskvaonline.ru/about/company",
    host_prod + "moskvaonline.ru/about/oplata-i-garantii",
    host_prod + "moskvaonline.ru/about/contacts",
    host_prod + "moskvaonline.ru/about/documents",
    host_prod + "moskvaonline.ru/about/personal-data",
    host_prod + "moskvaonline.ru/articles",
    host_prod + "moskvaonline.ru/articles/chem-otlichayutsya-routery",
    host_prod + "moskvaonline.ru/experts",
    host_prod + "moskvaonline.ru/experts/alisa-zhukova-id8",
    host_prod + "moskvaonline.ru/help",
    host_prod + "moskvaonline.ru/help/section-first",
    host_prod + "moskvaonline.ru/help/kak-podklyuchit-domashnij-internet-v-moskve",
    host_prod + "moskvaonline.ru/operatory",
    host_prod + "moskvaonline.ru/operatory/mts",
    host_prod + "moskvaonline.ru/operatory/mts/ratesmobile#tags#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/dlja-modema#tags",
    host_prod + "moskvaonline.ru/operatory/beeline/ratesmobile/dlja-noutbuka#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/bezlimitnyj-internet#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/vygodnye#tags",
    host_prod + "moskvaonline.ru/operatory/beeline/ratesmobile/semeinye#tags",
    host_prod + "moskvaonline.ru/operatory/beeline/ratesmobile/detskie#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/po-rossii#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/esim#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/perenos_nomera#tags",
    host_prod + "moskvaonline.ru/operatory/beeline/ratesmobile/bez-abonentskoj-platy#tags",
    host_prod + "moskvaonline.ru/operatory/tele-2/ratesmobile/mezhdunarodnye#tags",
    host_prod + "moskvaonline.ru/ratesmobile",
    host_prod + "moskvaonline.ru/ratesmobile/dlja-modema",
    host_prod + "moskvaonline.ru/ratesmobile/dlja-noutbuka",
    host_prod + "moskvaonline.ru/ratesmobile/bezlimitnyj-internet",
    host_prod + "moskvaonline.ru/ratesmobile/vygodnye",
    host_prod + "moskvaonline.ru/ratesmobile/bez-abonentskoj-platy",
    host_prod + "moskvaonline.ru/ratesmobile/semeinye",
    host_prod + "moskvaonline.ru/ratesmobile/detskie",
    host_prod + "moskvaonline.ru/ratesmobile/mezhdunarodnye",
    host_prod + "moskvaonline.ru/ratesmobile/po-rossii",
    host_prod + "moskvaonline.ru/ratesmobile/esim",
    host_prod + "moskvaonline.ru/ratesmobile/perenos_nomera",
    host_prod + "moskvaonline.ru/ratesmobile/bezlimitnaja-svjaz",
    host_prod + "moskvaonline.ru/ratesmobile/dlja-plansheta",
    host_prod + "moskvaonline.ru/operatory/mts/nomera",
    host_prod + "moskvaonline.ru/nomera",
    host_prod + "moskvaonline.ru/operatory/reviews",
    host_prod + "moskvaonline.ru/operatory/mts/reviews",
    host_prod + "moskvaonline.ru/feedback-operatory"
]

names_stage = [
    "Поиск без адреса",
    "Селект регион",
    "Главная с регионом",
    "Теговая для главной страницы Подключить Wi-Fi",
    "Теговая для главной страницы Подключить скоростной интернет",
    "Теговая для главной страницы Подключить дешевый интернет",
    "Теговая для главной страницы Подключить интернет 1 Гб/с",
    "Теговая для главной страницы Подключить проводной интернет",
    "Теговая для главной страницы Подключить оптоволокно",
    "Теговая для главной страницы Подключить интернет и ТВ",
    "Теговая для главной страницы Бесплатное подключение",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Дом",
    "Статус заявки",
    "Все районы",
    "Карта сайта",
    "Все регионы",
    "Рейтинг",
    "Рейтинг, тег Провайдер года",
    "Рейтинг, тег Качество и скорость",
    "Рейтинг, тег Лучшая цена",
    "Рейтинг, тег Сервис и техподдержка",
    "Отзывы в регионе",
    "Отзывы о провайдере",
    "Страница оставления отзыва",
    "Каталог провайдеров",
    "Страница вип-провайдера",
    "Страница провайдера Невип пров",
    "Тарифы вип-провайдера",
    "Тарифы вип-провайдера, тег Домашний интернет",
    "Тарифы вип-провайдера, тег Интернет + ТВ",
    "Тарифы вип-провайдера, тег Интернет + ТВ + мобильная связь",
    "Тарифы вип-провайдера, тег Интернет + Мобильная связь",
    "Тарифы вип-провайдера, тег Акции",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "Тарифы в регионе, тег Wi-Fi",
    "Тарифы в регионе, тег Быстрые",
    "Тарифы в регионе, тег Для игр",
    "Тарифы в регионе, тег Оптоволокно",
    "Тарифы в регионе, тег 1 Гб/с",
    "Тарифы в регионе, тег Проводной",
    "Для Бизнеса (экс В офис)",
    "На дачу",
    "Сотрудничество",
    "О нас",
    "Оплата и гарантии",
    "Контакты",
    "Документы",
    "Политика обработки персональных данных",
    "Отзывы о нас",
    "Все статьи блога",
    "Одна статья",
    "Все авторы блога",
    "Один автор",
    "Все разделы Частых вопросов",
    "Частые вопросы раздела Домашний интернет",
    "Ответ на один из частых вопросов",
    "Каталог мобильных операторов в регионе",
    "Страница Об операторе",
    "Тарифы оператора",
    "Тарифы оператора с тегом Для модема/роутера",
    "Тарифы оператора с тегом Для ноутбука",
    "Тарифы оператора с тегом Безлимитные",
    "Тарифы оператора с тегом Дешёвые",
    "Тарифы оператора с тегом Семейные",
    "Тарифы оператора с тегом Детские",
    "Тарифы оператора с тегом Связь по России",
    "Тарифы оператора с тегом eSIM",
    "Тарифы оператора с тегом Перейти со своим номером",
    "Тарифы оператора с тегом Роуминг за границей",
    "Тарифы операторов в регионе",
    "Тарифы операторов в регионе, тег Для модема/роутера",
    "Тарифы операторов в регионе, тег Для ноутбука",
    "Тарифы операторов в регионе, тег Безлимитные",
    "Тарифы операторов в регионе, тег Дешёвые",
    "Тарифы операторов в регионе, тег Семейные",
    "Тарифы операторов в регионе, тег Детские",
    "Тарифы операторов в регионе, тег Роуминг за границей",
    "Тарифы операторов в регионе, тег Связь по России",
    "Тарифы операторов в регионе, тег eSIM",
    "Тарифы операторов в регионе, тег Перейти со своим номером",
    "Красивые номера оператора",
    "Красивые номера в регионе",
    "Отзывы об операторах в регионе",
    "Отзывы об операторе",
    "Страница оставления отзыва об операторе",
]
