from config import host_stage, host_prod

urls = [
    host_stage + "moskvaonline.ru/",
    host_stage + "moskvaonline.ru/orders/tohome",
    host_stage + "moskvaonline.ru/address",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_stage + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_stage + "moskvaonline.ru/dom/ul-vinokurova-d-2-str1-id30677",
    host_stage + "moskvaonline.ru/doma-nzl?house_id=135510",
    host_stage + "moskvaonline.ru/reviews",
    host_stage + "moskvaonline.ru/rating/mts",
    host_stage + "moskvaonline.ru/feedback",
    host_stage + "moskvaonline.ru/rating",
    host_stage + "moskvaonline.ru/providers",
    host_stage + "moskvaonline.ru/providers/dom-ru",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/domashnij-internet",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rates",
    host_stage + "moskvaonline.ru/rates/domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-i-tv",
    host_stage + "moskvaonline.ru/rates/internet-tv-mobile",
    host_stage + "moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    host_stage + "moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    host_stage + "moskvaonline.ru/rates/internet-100-mbit",
    host_stage + "moskvaonline.ru/rates/internet-300-mbit",
    host_stage + "moskvaonline.ru/rates/internet-500-mbit",
    host_stage + "moskvaonline.ru/orders/sat",
    host_stage + "moskvaonline.ru/orders/office",
    host_stage + "moskvaonline.ru/all-districts",
    host_stage + "moskvaonline.ru/site-map",
    host_stage + "moskvaonline.ru/about/personal-data",
    host_stage + "moskvaonline.ru/about/documents",
    host_stage + "moskvaonline.ru/about/partners",
    host_stage + "moskvaonline.ru/about/company",
    host_stage + "moskvaonline.ru/about/contacts",
    host_stage + "moskvaonline.ru/about/oplata-i-garantii",
    host_stage + "moskvaonline.ru/select-region",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/internet-100-mbit",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/internet-300-mbit",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/internet-500-mbit",
    host_stage + "moskvaonline.ru/providers/actions/mts",
    host_stage + "moskvaonline.ru/providers/dom-ru/rates/online-kinoteatr",
    host_stage + "moskvaonline.ru/rates/online-kinoteatr",
    host_stage + "moskvaonline.ru/actions",
    host_stage + "moskvaonline.ru/business",
    host_stage + "moskvaonline.ru/contact-feedback"
]

names = [
    "Главная",
    "Поиск по адресу",
    "Карта покрытия",
    "Районы",
    "Улицы",
    "Золотой дом",
    "Обычный дом",
    "Отзывы в регионе",
    "Отзывы провайдера",
    "Страница оставления отзыва",
    "Рейтинг",
    "Каталог",
    "Страница провайдера",
    "Тарифы провайдера (тег Все)",
    "Тарифы провайдера, тег Домашний интернет",
    "Тарифы провайдера, тег Интернет + ТВ",
    "Тарифы провайдера, тег Интернет + ТВ+ мобильная связь",
    "Тарифы провайдера, тег Интернет + Мобильная связь",
    "Тарифы провайдера, тег Акции ",
    "Тарифы в регионе",
    "Тарифы в регионе, тег Домашний интернет",
    "Тарифы в регионе, тег Интернет + ТВ",
    "Тарифы в регионе, тег Интернет+ТВ+Мобильная связь",
    "Тарифы в регионе, тег Интернет + Мобильная связь",
    "Тарифы в регионе, тег Акции",
    "Тарифы в регионе, тег 100 Мб/с",
    "Тарифы в регионе, тег 300 Мб/с",
    "Тарифы в регионе, тег 500 Мб/с",
    "На дачу",
    "В офис",
    "Все районы",
    "Карта сайта",
    "Политика обработки перс данных",
    "Документы",
    "Сотрудничество",
    "О нас",
    "Контакты",
    "Оплата и гарантии",
    "Селект регион",
    "Тарифы провайдера, тег 100 Мб/с",
    "Тарифы провайдера, тег 300 Мб/с",
    "Тарифы провайдера, тег 500 Мб/с",
    "Тарифы провайдера, тег Акции ",
    "Тарифы провайдера, тег Онлайн кинотеатр",
    "Тарифы в регионе, тег Онлайн кинотеатр",
    "Акции в регионе",
    "Офисная заявка (старая)",
    "Форма обратной связи"
]

urls_prod = [
    host_prod + "moskvaonline.ru/",
    host_prod + "moskvaonline.ru/orders/tohome",
    host_prod + "moskvaonline.ru/address",
    host_prod + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164",
    host_prod + "moskvaonline.ru/address/%D0%B0%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9-id1164/%D1%83%D0%BB-%D0%B2%D0%B8%D0%BD%D0%BE%D0%BA%D1%83%D1%80%D0%BE%D0%B2%D0%B0-id298645",
    host_prod + "moskvaonline.ru/dom/ul-vinokurova-d-2-str1-id30677",
    host_prod + "moskvaonline.ru/doma-nzl?house_id=135510",
    host_prod + "moskvaonline.ru/reviews",
    host_prod + "moskvaonline.ru/rating/mts",
    host_prod + "moskvaonline.ru/feedback",
    host_prod + "moskvaonline.ru/rating",
    host_prod + "moskvaonline.ru/providers",
    host_prod + "moskvaonline.ru/providers/dom-ru",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/domashnij-internet",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/internet-i-tv",
    host_prod + "moskvaonline.ru/providers/rostelecom/rates/internet-tv-mobile",
    host_prod + "moskvaonline.ru/providers/mts/rates/internet-i-mobilnaya-svyaz",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/nedorogoj-domashnij-internet",
    host_prod + "moskvaonline.ru/rates",
    host_prod + "moskvaonline.ru/rates/domashnij-internet",
    host_prod + "moskvaonline.ru/rates/internet-i-tv",
    host_prod + "moskvaonline.ru/rates/internet-tv-mobile",
    host_prod + "moskvaonline.ru/rates/internet-i-mobilnaya-svyaz",
    host_prod + "moskvaonline.ru/rates/nedorogoj-domashnij-internet",
    host_prod + "moskvaonline.ru/rates/internet-100-mbit",
    host_prod + "moskvaonline.ru/rates/internet-300-mbit",
    host_prod + "moskvaonline.ru/rates/internet-500-mbit",
    host_prod + "moskvaonline.ru/orders/sat",
    host_prod + "moskvaonline.ru/orders/office",
    host_prod + "moskvaonline.ru/all-districts",
    host_prod + "moskvaonline.ru/site-map",
    host_prod + "moskvaonline.ru/about/personal-data",
    host_prod + "moskvaonline.ru/about/documents",
    host_prod + "moskvaonline.ru/about/partners",
    host_prod + "moskvaonline.ru/about/company",
    host_prod + "moskvaonline.ru/about/contacts",
    host_prod + "moskvaonline.ru/about/oplata-i-garantii",
    host_prod + "moskvaonline.ru/select-region",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/internet-100-mbit",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/internet-300-mbit",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/internet-500-mbit",
    host_prod + "moskvaonline.ru/providers/actions/mts",
    host_prod + "moskvaonline.ru/providers/dom-ru/rates/online-kinoteatr",
    host_prod + "moskvaonline.ru/rates/online-kinoteatr",
    host_prod + "moskvaonline.ru/actions",
    host_prod + "moskvaonline.ru/business",
    host_prod + "moskvaonline.ru/contact-feedback"
]
